### ISSUE TITLE
Photo Downloader doesn't find all Meetup photo folders/albums

### ISSUE THREAD

**Issue by GoogleCodeExporter** [krcourville/meetup-photo-download#12]
```
Meetup displays 20 photo folders at a time. You can then select subsequent 
groups of 20 to display. Downloader identifies and allows me to download the 
first 10 pages (200 folders) perfectly, but the 11th page's folders are not 
found by Downloader.


```

Original issue reported on code.google.com by `raybe...@gmail.com` on 16 Jul 2011 at 11:03

**Comment by x3mjp3x** [comment]
Hi Ken, I stumbled on your app yesterday while trying to find a way to download my past photo albums from my Meetup group since I lost so many of the pics from a hard drive failure. Now Meetup is the only place I have them stored. I see the Downloader doesn't pull up any more than 200 albums as the other comment noted. Has there been any development in the software since they will allow it to pull more than 200?

**Comment by krcourville** [comment]
Hello,

Thank you for your interest in MPDL!

I can no longer support this project as open source.  This issue has been addressed in [Easy Photo Downloader](https://easydownload.photos/).  

For further assistance, please use the feedback mechanisms provided at [Easy Photo Downloader](https://easydownload.photos/).
